[package]
name = "tax_rules"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8.0", features = [ "runtime-tokio", "tls-native-tls", "postgres" ] }